### ISSUE TITLE
Run tests on CPU and GPU

### ISSUE THREAD

**Issue by jeffjennings** [MPoL-dev/MPoL#116]
**Is your feature request related to a problem or opportunity? Please describe.**
Tests currently only run on a CPU implementation of mpol.  

**Describe the solution you'd like**
Tests should also run on GPU to ensure changes to codebase don't break GPU functionality.

**Additional context**
Not sure of best GPU platform to integrate into the github actions test workflow. Ian mentioned RoarCollab.

**Comment by iancze** [comment]
One possibility is to have a SLURM script on Roar that requests access to a GPU and then runs the full test suite and docs build. This wouldn't be continuously integrated in the sense that all pushes to Github are, but if we remember to run it periodically we could probably catch at least a few potential bugs.

**Comment by iancze** [comment]
We agreed that 
* we should write tests that are GPU capable
* for now, user tests on local GPU resources are adequate, since there are no free or easily configurable GPU runners
