### ISSUE TITLE
Documentation on "packed" image cube format

### ISSUE THREAD

**Issue by iancze** [MPoL-dev/MPoL#13]
**Is your feature request related to a problem or opportunity? Please describe.**
It would be helpful to have a short description in the documentation visualizing what we mean by "packed" image or visibility cube format. I.e., after np.fft.fftshift has been applied to a normal cube. The fftshift operation works only along the RA and DEC axes to prepare the cube for a 2D FFT. The velocity/frequency axis remains untouched.

For image cubes, we are calling

* "sky_cube" -> the normal orientation of an image on the sky, i.e., for plotting. RA increases to the *left* 
* "packed_cube" -> the application of fftshift(flip(sky_cube)) along the RA and DEC axes. 

For visibility cubes, there is no corresponding "sky," rather just the way we want the array to look on the ground. "u" increases to the right.

This is a rough sketch showing how the cubes are related. 

<img width="827" alt="Screen Shot 2021-05-19 at 8 14 28 PM" src="https://user-images.githubusercontent.com/467948/118900427-efc75280-b8de-11eb-8c1a-55b19bf5e84d.png">

Also probably worthwhile to review the developer documentation on [Units and Conventions](https://mpol-dev.github.io/MPoL/units-and-conventions.html) describing how arrays are packed.

- [ ] why this format is required in the first place (for the FFT conventions)
- [ ] how this is used internally, and what the roles of the `sky_cube` functions are
- [ ] [utils](https://github.com/MPoL-dev/MPoL/blob/main/src/mpol/utils.py) routines for shifting need documentation

For a reference implementation of how we use these packed formats, see the flow of an image cube through [ImageCube](https://github.com/MPoL-dev/MPoL/blob/main/src/mpol/images.py#L152) to a [sky_cube](https://github.com/MPoL-dev/MPoL/blob/main/src/mpol/images.py#L229).

**Describe the solution you'd like**
Write a short `.rst` file either as part of "units and conventions" or near it.

**Comment by trq5014** [comment]
Thank you for updating this! It really helped clear up some of my confusion here. This issue will hopefully be resolved soon now.
