### ISSUE TITLE
Memory profiling

### ISSUE THREAD

**Issue by jeffjennings** [MPoL-dev/MPoL#136]
**Is your feature request related to a problem or opportunity? Please describe.**
Especially with large datasets, it would be good to profile memory usage and if necessary, make sure not to pass too much to the GPU at once and/or do operations in chunks.

**Describe the solution you'd like**
Run a memory profiler to check both RAM and VRAM in a fit loop.

**Comment by iancze** [comment]
[memray](https://bloomberg.github.io/memray/index.html) seems like a modern profiler for the CPU operations. Might need something NVIDIA-specific for the GPU operations.

**Comment by jeffjennings** [comment]
Closing as deprecated by v0.3

**Comment by iancze** [comment]
This is an important topic, but the issue could be more specific. What are the time/memory intensive parts of the workflow that should be profiled?

**Comment by jeffjennings** [comment]
Yeah I would suggest keeping this issue closed and creating a new, more targeted issue once there's a specific part of the code that needs to be profiled for a use case.
