### ISSUE TITLE
Direct `.forward()` calls not recommended

### ISSUE THREAD

**Issue by kadri-nizam** [MPoL-dev/MPoL#151]
I noticed in the code base that `model.forward()` is being called directly instead of `model()`. PyTorch devs recommend against the former since the `__call__` dunder method for the latter has [special hooks included in them](https://github.com/pytorch/pytorch/blob/36dfbb08f3dce0b082645e2499d8ddd7cde68fde/torch/nn/modules/module.py#L1494).

**Comment by iancze** [comment]
Good catch. We should audit the codebase and change the `model.forward()` calls to `model()` calls.
