### ISSUE TITLE
Update SimpleNet with NuFFT option to predict loose visibilities

### ISSUE THREAD

**Issue by iancze** [MPoL-dev/MPoL#161]
It would probably streamline many a workflow if [SimpleNet](https://mpol-dev.github.io/MPoL/api.html#mpol.precomposed.SimpleNet) had a method to produce "loose" visibilities corresponding to the current state of `icube`. This would be very useful for residual visualization purposes. For example, using [DirtyImager](https://mpol-dev.github.io/MPoL/api.html#mpol.gridding.DirtyImager) and TensorBoard within a training loop, or just as a final check at the end of the process.

I would imagine this class method would look something like

```
def get_loose_visibilities(self, uu, vv):
   # uu and vv are either (nvis) or (nchan, nvis) shape arrays
   # create NuFFT object 
   vis = nufft_ob(self.icube(), uu, vv)
   return vis
```

The way we currently wrapped the NuFFT, it expects to know the uu and vv arrays upon initialization. This is to make its usage inside of an optimization loop more efficient, so that the `sparse_matrices` do not need to be rebuilt on each call. But it doesn't have to be this way. We could modify the `NuFFT.forward` routine to take in new (uu, vv) points and predict to those using the (less precise) table interpolation mode, as suggested in the pseudocode above. That way the SimpleNet could be used to translate the current state of the icube to a variety of proposed uu or vv points that are not known upon initialization. I think that requiring `uu` and `vv` points at SimpleNet initialization would also confuse the user.

The main `forward` call of SimpleNet should probably still use the GriddedDataset and indexing framework, since this will be faster when used in an optimization loop. 

It would also help to update the [Intro to RML with MPoL](https://mpol-dev.github.io/MPoL/ci-tutorials/optimization.html) tutorial to reflect these changes. At the same time, we should also make it clear that the users do not *have* to use SimpleNet and we can give them an example of how to compose their own modules together, by referencing the source code of SimpleNet:

https://github.com/MPoL-dev/MPoL/blob/8837f77f54453b74845f68fe4ebe00346f56118c/src/mpol/precomposed.py#L60-L70

**Comment by jeffjennings** [comment]
I coincidentally just added a variant of this in #146 ([here](https://github.com/MPoL-dev/MPoL/blob/7bcc50357ce09a198f700c6ae1b41782088c158b/src/mpol/fourier.py#L454)) in order to dirty image residuals in a train loop - but it still requires specifying (u,v) on nufft initialization.

**Comment by iancze** [comment]
Great! I might steal this and put it into SimpleNet, too.

**Comment by jeffjennings** [comment]
Whatever works - and feel free to change it of course; e.g. to just produce model, not residual, vis.
