### ISSUE TITLE
Distinguishing optimal images

### ISSUE THREAD

**Issue by jeffjennings** [MPoL-dev/MPoL#215]
**Is your feature request related to a problem or opportunity? Please describe.**
Even with reasonably large dartboard cells, the loss profiles in a cross-val loop remain pretty similar (see e.g. #214). I'm not sure if many regularizer/strength combinations fitting the observed data very similarly indicates the model just needs more data to be able to distinguish between optimizations using different regularizer strengths, or even different regularizers. Maybe the predictive accuracy of the model to unobserved points scales strongly with the number of points?

**Describe the solution you'd like**
Not sure how much of an altered modeling approach this would require. Is there a better way than CV to distinguish between models?

**Describe alternatives you've considered**
Within the CV framework, I could test how much of a difference it makes to:
- decrease the number of k-folds
- increase the dartboard cell size
- compare cross-val results for the same dataset when different fractions of it are withheld entirely from the modeling process (to see how strongly the inference scales with the number of points)
- other ways to distinguish better between cross-vals with different regularizers/strengths? I'm sure there are standard ML ways of doing this...

**Comment by jeffjennings** [comment]
Best model of this set, identified by accuracy of visibility fit:
![IMLup_dartboard_10kfolds_{'sparsity' {'lambda' 0 0001, 'guess' False}}_projected_visibilities](https://github.com/MPoL-dev/MPoL/assets/16950784/daf9277b-1e64-495f-80af-4bc6b63f6f42)

and image of residual visibilities:
![IMLup_dartboard_10kfolds_{'sparsity' {'lambda' 0 0001, 'guess' False}}_image_comparison](https://github.com/MPoL-dev/MPoL/assets/16950784/c8f194ff-25c2-4ea3-b53d-80389992e421)

**Comment by jeffjennings** [comment]
I ran a train/test loop with the .asdf dataset of IM Lup with no averaging, and am getting a very similar result to that with the time- and frequency-averaged dataset I've been using. It doesn't seem like this is the source of the poor fit at short baselines.

Fit with .asdf dataset:
![IMLup_dartboard_1kfolds_{'sparsity' {'lambda' 0 0001, 'guess' False}}_train_diag_kfold0_epoch01987_averaged_data](https://github.com/MPoL-dev/MPoL/assets/16950784/a7e081cd-e614-4c85-b463-7b78168b3a3c)

Fit with averaged dataset: 
![IMLup_dartboard_1kfolds_{'sparsity' {'lambda' 0 0001, 'guess' False}}_train_diag_kfold0_epoch01961_asdf_data](https://github.com/MPoL-dev/MPoL/assets/16950784/dd765b55-5a17-4679-a7d4-579821d276d2)

**Comment by iancze** [comment]
Interesting, what do the residuals look like in terms of their sigma, for real and imaginary?

**Comment by jeffjennings** [comment]
I'm not sure, the NuFFT also crashes. But since the images are effectively identical, the model and residual visibilities should be too. E.g. thei images' total flux is the same to 2 parts in 1000, so they're both underfitting to the same degre at short baselines. If you want to run more tests with the full dataset, it's probably more practical to run on your cluster. I can send a script to reproduce the pipeline in its current state.

**Comment by jeffjennings** [comment]
Yeah I made an issue this morning to that end, #224. Let me know how it goes!

**Comment by jeffjennings** [comment]
Closing as out of date and out of scope for v0.3 redesign
