### ISSUE TITLE
Add Zawadzki et al. to citation

### ISSUE THREAD

**Issue by iancze** [MPoL-dev/MPoL#226]
We should also add [Zawadzki+23 PASP](https://ui.adsabs.harvard.edu/abs/2023PASP..135f4503Z/abstract) to the citation info. If/when the JOSS paper is submitted and accepted, both should be suggested as relevant citations.

**Comment by jeffjennings** [comment]
Great. 

"If/when"- I think there's no reason not to submit a JOSS paper. Its citation could replace the Zenodo citation.

**Comment by iancze** [comment]
I meant more about the acceptance, didn't want to be presumptuous ;)

**Comment by jeffjennings** [comment]
Ah ok gotcha. Updating things with the accepted JOSS paper is referenced in #203, so #228 should close this.
