### ISSUE TITLE
GPU Tutorial

### ISSUE THREAD

**Issue by iancze** [MPoL-dev/MPoL#28]
**Is your feature request related to a problem or opportunity? Please describe.**
One great benefit of PyTorch is the ability to easily run on GPU-accelerated hardware for substantial speedups. Currently, none of the tutorials show off this functionality, though it exists.

**Describe the solution you'd like**
At minimum, a section of a tutorial incorporating transfer code like in the [PyTorch tutorial](https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#training-on-gpu). For monolithic batches (common to most simple RML imaging problems), GPU accelerated training loops are the quickest way to a significant training speedup. 

**Alternative solutions**
For batched training workflows (e.g., where each batch is an execution block of a measurement set), a distributed training loop (across multiple CPUs or even GPUs) has the potential to be faster.

**Comment by trq5014** [comment]
I was able to download and install Cuda for gpu use, however, I am not able to get pytorch to be able to see it (torch.cuda.is_available() returns false). I have restarted my computer and checked the $CUDA_PATH variables and everything looks good. I can use numba with the gpu as far as I can tell, but pytorch wont recognize it. Does pytorch require the TCC driver?

![image](https://user-images.githubusercontent.com/84112808/120385089-fbf6db00-c2f4-11eb-9938-a8744bd57a67.png)
![image](https://user-images.githubusercontent.com/84112808/120387345-c99aad00-c2f7-11eb-8c0c-244c5b99569e.png)

**Comment by iancze** [comment]
I'm not whether you need to specifically configure CUDA as long as you install the right version of PyTorch depending on your hardware.

There is a little selector install widget on the Pytorch homepage: https://pytorch.org/ that might give a hint of what to try.

It looks like for Windows you might need to do something like 
`
pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`

If this resolves it, we should make a note in the installation instructions. I've just used default `pip install torch torchvision` and that's always seemed to work picking up the GPU on the Roar compute environment.

**Comment by trq5014** [comment]
Sounds good, I will check on this and get back with any further issues. This specific issue I am having is not well documented online so it will be helpful to include this in the tutorial

**Comment by trq5014** [comment]
Using that worked, the pip install torch torchvision was not working on my system for whatever reason. I will include this fix in the tutorial

**Comment by iancze** [comment]
Great! A brief note in the tutorial would be good, as well as a short note about the possibility of GPU-specific installs in the "Installation.rst" file would be great, thanks!

**Comment by trq5014** [comment]
Would it be possible to include a screenshot (.png) of the Install PyTorch section on their homepage for greater clarification on this in the .rst file?

**Comment by iancze** [comment]
It's possible, but probably not necessary. I would just add a sentence or two that torch may need to be (re)installed separately and that more information is available on the pytorch homepage.

**Comment by trq5014** [comment]
For the GPU tutorial itself, would it be sufficient to follow the Optimization Loop tutorial on the documentations site and show this running on the GPU and then compare the time of the loop ran on the CPU to that with the GPU? Or would you prefer something else? Also, using the GPU may be worth adding to the Issue #25 chapters
