### ISSUE TITLE
ImageCube FITS export gives incorrect RA/DEC scale.

### ISSUE THREAD

**Issue by iancze** [MPoL-dev/MPoL#34]
**Describe the bug**
ImageCube FITS export gives incorrect RA/DEC scale. Somethings's too large by a factor of 1000 or more.

My suspicion is that there's an incorrect [conversion from arcseconds to degrees](https://github.com/MPoL-dev/MPoL/blob/main/src/mpol/images.py#L263).

We should fix this in the code, but also develop a corresponding test for FITS export to make sure we're exporting what we want to be exporting.

**Comment by trq5014** [comment]
When going over the code for ImageCube.to_FITS() I found that there was a conversion from arcseconds to degrees using _arcseconds * 180 / pi_ (conv1). I printed out the **CDELT1** and **CDELT2** values for this conversion and the conversion using _arcseconds / 3600_ (conv2). The results for conv1 were: **CDELT1/CDELT2 = 0.28647889756541** while the results for conv2 were: **CDELT1/CDELT2 = 1.3888... e-06**. The input value for _cellsize_ (the variable used in the arcseconds conversion) was 0.005. Which, if I understand this correctly, is the same value as presented by conv2 (0.005/3600 = CDELT1/CDELT2). I opened both of the resulting fits files in AstroImageJ to check the dimensions. conv1's DEC ranged from +75:57:31.63 to -00:01:148.10 and conv1's RA ranged from 23:59:19.194 to 05:03:48.357 while conv2's DEC ranged from +00:00:04.00 to +00:00:00.00 and conv2's RA ranged from 00:00:00.00 to 00:00:00.266. The image is 800x800 pixels, and each pixel represents 0.005 arcseconds (_cellsize_). Am I misunderstanding something, or shouldn't the fits image's DEC have a range of 4 arcseconds?

**Comment by iancze** [comment]
I'm not sure what your ratios of `CDELT1/CDELT2` are signifying. Are you just saying that they are the same value? They should be, generally CDELT1 == CDELT2

If the image is 800 pixels and each pixel is 0.005 arcseconds, then yes, the image width should be 4 arcseconds wide. It looks like your "conv2" is the correct solution, then? 

If you're satisfied with the solution, it would be great to have this as a pull request back into main (when you're ready w/ tests). Thanks!

**Comment by trq5014** [comment]
Sounds good, and yes I meant it as CDELT1 _and_ CDELT2 = _value_, I see where this may have been confusing.
