### ISSUE TITLE
HD 143006 high spatial frequency noise

### ISSUE THREAD

**Issue by iancze** [MPoL-dev/MPoL#64]
**Describe the bug**
Not so much of a software bug as more of a conceptual hurdle that we want to understand. Why do unregularized (or loosely regularized) fits to real data end up with this popcorn pattern?

Upper left: optimized image. Lower left: log(amplitude) of Fourier cube. Upper right: Uniformly-weighted image corresponding to residuals, Lower Right: log(amplitude) of residuals in Fourier plane. Note how the residuals only really make sense where the data was gridded, the rest of the plot is the same as the lower left.

<img width="817" alt="Screen Shot 2021-06-01 at 10 21 58 AM" src="https://user-images.githubusercontent.com/467948/120410976-054a6c80-c322-11eb-97c8-77c66bbe2877.png">

**To Reproduce**
Run an optimization loop to full convergence with no priors other than image positivity.

**Additional context**
* What are the spatial frequencies of the noise? I.e., what kilolambda u/v/q do the popcorn ripples correspond to?
* What is the data doing at these frequencies (e.g., is it "noise dominated")? How does the image compare to dirty images produced with uniform, robust=0, and natural weighting?
* What does the gridded data corresponding to the dirty image look like at these frequencies under uniform weighting? Robust? Natural? My guess is that the gridded data will look very similar to a uniformly gridded set of data.
* Is this phenomenon limited to real data only (suggesting a calibration problem), or does it appear in simulated data too? A similar type of issue crops up in the [unregularized fit](https://mpol-dev.github.io/MPoL/tutorials/crossvalidation.html#Results) of the optimization tutorial (which uses simulated data), suggesting it has something to do with when the visibilities at higher spatial frequencies start to become noise-dominated.

**Comment by trq5014** [comment]
I reran the exact same code that we are using for Part 2 of the tutorial where we do get some of the popcorn effect using the mock alma dataset and it did not appear that any popcorning occured. I'm going to go a little further and see if I can get the affect to occur, but it is looking like its a real-data problem.

**Comment by iancze** [comment]
Though not as bad as the HD 143006 dataset, I do see some similar effects in the [Cross Validation tutorial](https://mpol-dev.github.io/MPoL/ci-tutorials/crossvalidation.html). 

One thing that has changed in the past few weeks is that I updated the .npz datasets to fix the incorrect scaling of the weights that is default from CASA and simobserve. So the mock ALMA logo datasets have changed since you first saw them a few weeks ago. Are you using the latest dataset available from https://zenodo.org/record/4930016/files/logo_cube.noise.npz ?

The old version of the ALMA Logo datasets actually had no "noise" added, they were purely signal. So, they weren't very representative datasets in that regard :) 

If you are using the new version and you still see this, then I think the difference might be the S/N distribution of the data. The HD 143006 most likely has a larger number of long baselines that are lower S/N. And this is something that would be great to dig into and compare, to try to understand why the popcorning might be occurring in one dataset but not the other.

**Comment by trq5014** [comment]
I was using that one. I saw some minor, wavy-looking effects which I guess could resemble the popcorning slightly. For reference, I attached the most "popcorny" image that I have managed to produce so far. 
![image](https://user-images.githubusercontent.com/84112808/124673251-85667380-de86-11eb-85bd-0d4ca613e531.png)
 It may be worth trying this with another real-world dataset to see if it occurs. I'm not sure how difficult it is to extract the visibilities using casa, but I could try this if you think it would give us some more insight.

**Comment by iancze** [comment]
This image looks suspiciously like the ones I recall from the dataset with no noise. It's possible that the astropy download function is using a stale cache and not updating with the new file. You can delete the cache [as described in the developer docs](https://mpol-dev.github.io/MPoL/developer-documentation.html#test-cache) and then the next run should download the new dataset from scratch. You can also verify that it's the updated dataset with noise by running an `md5sum` check on the *.npz file (available on linux command line). The correct md5sum should be `3b4b7db6ca3e6e2d5183e003fa95b519` as indicated on the [Zenodo repo](https://zenodo.org/record/4930016#.YOTjExNKidY).

If this is indeed the new file, then what a great combination of priors! This looks much better than I was able to achieve in the cross validation tutorial. Can you compare the prior/regularizer terms that you are using to that tutorial?

**Comment by trq5014** [comment]
Unfortunately, you were right. I updated the link, but the cache system still just pulled the old file. The same code that produced the image above produced this image with the new file:
![image](https://user-images.githubusercontent.com/84112808/124689974-7fcd5580-dea7-11eb-90b1-d2dbaf01acd6.png)

It seems that the popcorn effect may stem from noise then?

**Comment by iancze** [comment]
Ok, that's good you were able to identify the stale cache. As the famous quote goes... [there are only two hard things in computer science](https://martinfowler.com/bliki/TwoHardThings.html), cache invalidation being one of them.

Yes, most likely the popcorn effect is the result of the longer baselines being lower S/N. Per "loose" visibility sample, the noise is approximately constant. But as you get to longer and longer baselines there are 

1) fewer visibility samples, which means the ability to average over many samples within a grid cell is diminished
2) most "natural" images contain less power at higher spatial frequencies. You can see this effect in the lower panels of the image in the first post. There's a point around 5,000 klambda where the amplitude pattern goes from something that looks structured to something that looks more like noise.

Both of these effects constitute a double whammy in knocking the signal-to-noise ratio, which means that in some grid cells, especially those at higher spatial frequencies, noise will dominate over the signal. The challenge here is developing a set of priors that will help us regularize the model fit when/where visibilities become noise dominated.

For this and the HD 143006 images, it would be helpful if you could estimate the spatial frequency of the popcorn pattern. I.e., assuming that the peaks of the popcorn pattern correspond to the peaks of a sine wave, what spatial frequency in kilolambda is that? It might be easiest to first calculate the frequency in cycles / arcsecond, and then convert that to cycles / radian, which is equivalent to units of lambda.

**Comment by trq5014** [comment]
> For this and the HD 143006 images, it would be helpful if you could estimate the spatial frequency of the popcorn pattern. I.e., assuming that the peaks of the popcorn pattern correspond to the peaks of a sine wave, what spatial frequency in kilolambda is that? It might be easiest to first calculate the frequency in cycles / arcsecond, and then convert that to cycles / radian, which is equivalent to units of lambda.

Do you mean within the Sky Cube here?

I also thought it might be worth adding the `log_figure` for the mock alma dataset here as something doesn't look right here. Maybe you can understand/explain why the residuals has as strong of an image as the sky cube and why the other plots are extremely faint.
![image](https://user-images.githubusercontent.com/84112808/124928607-bb623f80-dfcd-11eb-8135-123bf6bd111c.png)

**Comment by iancze** [comment]
A few extra things from our discussions today:

1) The strong "ghost" image in the residuals could be a result of not running the optimization to full convergence. If things are fully converged, then this could be an example where the prior regularization is set to be too strong and pulls the fit away from the data. What regularizers are you using, with what strengths?

2) The values of the gridded visibilities can be examined as part of the `gridder.vis_gridded` attribute, after the `gridder.get_dirty_image` or `gridder.to_pytorch_dataset` routines are called. These would be interesting to plot up for the dirty image examples with uniform, natural, and robust = 0.0 weighting schemes.

3) We also discussed that it might be worthwhile adding an `n_vis_gridded` attribute (for the number of visibilities that were gridded per cell). But in the meantime, you can see the effective sensitivity of each cell using the `gridder.weight_gridded` attribute, which is only available after a call to `gridder.to_pytorch_dataset`, because the weights lose their statistical meaning for anything other than uniform weighting. (@ryanaloomis)

**Comment by iancze** [comment]
Closing this issue, as I think we've identified the source of the "popcorning" as the unrestricted influence of noisy long-baselines, coupled with the strict image positivity prior. I think we've discussed the original issue sufficiently (here and through other forums), and the focus has now moved on to examining the effects of regularizers (#76).
