### ISSUE TITLE
Loss function and regularizer "gallery"

### ISSUE THREAD

**Issue by iancze** [MPoL-dev/MPoL#76]
**Is your feature request related to a problem or opportunity? Please describe.**
A tutorial or document exploring the how different regularizers penalize images, and what their strengths are w.r.t. to the "truth" image.

**Describe the solution you'd like**
A tutorial that creates RML images using different prior settings, and the compares these total loss values to the score that would be achieved by the "perfect" image and corresponding visibilities.

* Synthesize a mock dataset using some interesting images. 
* Calculate the loss and the prior values.

Creating such a dataset will be a lot easier after we implement #17

**Comment by briannazawadzki** [comment]
Great idea! Here are the images and residuals.

[prior_grid_images.pdf](https://github.com/MPoL-dev/MPoL/files/6919066/prior_grid_images.pdf)
[prior_grid_resids.pdf](https://github.com/MPoL-dev/MPoL/files/6919068/prior_grid_resids.pdf)

Each column shows a different prior (specified at the top). The lambda values for each prior are given on each plot. Note that entropy also has a prior intensity parameter, and I used 1e-7 for all of them.

**Comment by iancze** [comment]
Effectively closed by figures and text in Zawadzki et al.: https://ui.adsabs.harvard.edu/abs/2022arXiv220911813Z/abstract
