### ISSUE TITLE
Investigate solutions to unregularized fits

### ISSUE THREAD

**Issue by iancze** [MPoL-dev/MPoL#98]
**Is your feature request related to a problem or opportunity? Please describe.**
It's possible to run RML using only a NLL loss. This essentially yields just a "maximum likelihood" image without the regularization part. The only real regularization we have built in is the fact that pixel intensities are non-negative by construction (via the softplus transformation). These images are created with very small values of regularizers, essentially NLL loss. We could also do this directly.

<img width="823" alt="Screen Shot 2022-09-14 at 4 03 31 PM" src="https://user-images.githubusercontent.com/467948/190251458-e6636944-620b-481e-bd97-84e0428ee5b6.png">

The issue really concerns: **why is this,** and why is it different than what the dirty image looks like?

Our suspicion is that 
1. the dirty image is just *one* of many maximum likelihood images, so there's no guarantee that they will look exactly the same
2. the softplus transformation does actually impose regularization on the image, so it's not an apples-to-apples comparison
3. the UV cells corresponding to higher spatial frequencies will have the lowest S/N (a combination of low inherent signal power *and* an increase in noise because of lower number of visibilities per cell and greater phase noise. These lower S/N cells introduce noise at high spatial frequencies, causing this stippled pattern.

Potential actions towards confirming/refuting our suspicions:
* Compare likelihood values between dirty image and ML image found with only NLL loss. 
* Compare visibility grid values between image. Are the empty UV cells in the NLL image taking on large values? Does the image still look the same if we impose UV sparsity on the fit?
* Calculate the chi^2 values for each grid cell for the dirty image and NLL loss

**Comment by iancze** [comment]
@jeffjennings Do you think you could screenshot one or two of your 1D analysis figures that you showed in group meeting and paste them here? I think that would provide sufficient documentation that indeed our suspicions were correct (esp. regarding point 3) and then we can close this issue.

**Comment by jeffjennings** [comment]
Unregularized image for mpol modeling of noisy mock dataset: 
![mock_test_noisy](https://user-images.githubusercontent.com/16950784/229639649-bca6785f-0414-45a7-b28e-440ff9fabb22.png)

1d plots of same:
![mock_test_1d_noisy](https://user-images.githubusercontent.com/16950784/229639555-30f7f1a1-e06f-4bfe-ac51-55c1763edf1a.png)
